import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  resolve: {
    // Mirror apps/web's "@/*" -> "src/*" tsconfig path so route tests resolve.
    // Key is "@" (not "@/"): the alias matcher requires a "/" AFTER the key, so
    // this matches "@/lib/..." but never the "@voxscore/*" workspace pkgs.
    alias: {
      '@': fileURLToPath(new URL('./apps/web/src', import.meta.url)),
    },
  },
  test: {
    include: [
      'packages/**/src/**/*.{test,spec}.ts',
      'apps/web/src/**/*.{test,spec}.ts',
      // Mobile pure-logic tests (e.g. the api client). These mock './supabase'
      // and any expo native modules, so they run in the node env like the rest.
      'apps/mobile/src/**/*.{test,spec}.ts',
    ],
    coverage: {
      provider: 'v8',
      // Coverage stays packages-only (100% thresholds). App routes are exercised
      // by their own tests but not held to the package coverage bar.
      include: ['packages/**/src/**/*.ts'],
      exclude: [
        'packages/**/src/**/*.{test,spec}.ts',
        'packages/**/src/index.ts',
        // Type-only package: no runtime code to cover (regenerated by db:types).
        'packages/db/**',
      ],
      thresholds: {
        lines: 100,
        functions: 100,
        statements: 100,
        branches: 95,
      },
    },
  },
});
