import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['packages/**/src/**/*.{test,spec}.ts'],
    coverage: {
      provider: 'v8',
      include: ['packages/**/src/**/*.ts'],
      exclude: [
        'packages/**/src/**/*.{test,spec}.ts',
        'packages/**/src/index.ts',
        // Type-only package: no runtime code to cover (regenerated by db:types).
        'packages/db/**',
      ],
      thresholds: {
        lines: 100,
        functions: 100,
        statements: 100,
        branches: 95,
      },
    },
  },
});
